defaults:
  - override hydra/sweeper: optuna

hydra:
  # run:
  #   dir: &now_dir logs/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: logs/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  sweeper:
    sampler:
      seed: 234
    direction: minimize
    storage: null
    n_trials: 20
    n_jobs: 1

# Comment about experiments.
comment: ~

log_dir: &now_dir "${hydra:sweep.dir}/${hydra:sweep.subdir}"
# log_dir: *now_dir
epochs: 1000
verbose: 1
batch_size: 32
workers: 1
use_multiprocessing: false
use_mixed_float16: false
callback_config:
  early_stopping_config:
    monitor: "val_loss"
    patience: 50
    verbose: 1
  model_checkpoint_config:
    filepath: "${log_dir}/{epoch}_{val_loss:.4f}.h5"
    save_best_only: true
    save_weights_only: true
    monitor: "val_loss"
    verbose: 1
    remove_non_best_weights: true
  reduce_lr_on_plateau_config:
    monitor: "val_loss"
    factor: 0.1
    patience: 16
    min_lr: 1.0e-7
    verbose: 1
  tensor_board_config: null  # Do not add callback, if null
    # log_dir: "${log_dir}"

# model settings
model_config:
  name: "sample_model_name"
  summarize: false
  # about model shape
  input_image_shape: ${as_tuple:256,256,3}
  num_classes: 26

optimizer_config:
  learning_rate: 1.0e-4
  optimizer: "Adam"
  use_gradient_accumulation: true
  accumulation_steps: 4
loss: "binary_crossentropy"
loss_weights: ~
metrics: "accuracy"

# data settings
data_config:
  shuffle: true
  augment_all_combination: false
  augment_setting_path_to_save: "${log_dir}/${hydra:job.num}/augment_setting.yaml"
