defaults:
  - override hydra/sweeper: optuna

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: logs/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  sweeper:
    sampler:
      seed: 234
    direction: minimize
    storage: null
    n_trials: 20
    n_jobs: 1

# Comment about experiments.
comment: ~

epochs: 1000
verbose: 1
batch_size: 32
workers: 1
use_multiprocessing: False
use_mixed_float16: False
callback_config:
  early_stopping_config:
    monitor: "val_loss"
    patience: 100
    verbose: 1
  model_checkpoint_config:
    filepath: "{epoch}_{val_loss:.4f}.h5"
    save_best_only: true
    save_weights_only: true
    monitor: "val_loss"
    verbose: 1
    remove_non_best_weights: true
  reduce_lr_on_plateau_config:
    monitor: "val_loss"
    factor: 0.1
    patience: 30
    min_lr: 1.0e-8
    verbose: 1
  tensor_board_config: null # Do not add callback, if null

# model settings
model_config:
  name: "sample_model_name"
  summarize: false
  # about model shape
  input_image_shape: ${as_tuple:224,224,3}
  num_classes: 26

optimizer_config:
  learning_rate: 1.0e-4
  optimizer: "Adam"
  use_gradient_accumulation: false
  accumulation_steps: 4
  clipnorm: null
  global_clipnorm: null
loss: "categorical_crossentropy"
loss_weights: ~
metrics: "accuracy"

# data settings
data_config:
  shuffle: true
  augment_all_combination: false
  augment_setting_file_name: "augment_setting.yaml"
